[workspace]
resolver = "2"

members = [
  "libkstat-sys/",
  "kstat-rs",
]

default-members = [
  "libkstat-sys/",
  "kstat-rs",
]

[workspace.dependencies]
libc = "0.2"
thiserror = "1"
libkstat_sys = { path = "libkstat-sys" }
subprocess = "0.2"
